### PR TITLE
Make react a peer dep and add 17

### PR DESCRIPTION
**Pull request by maclockard**

### CODE REVIEW

**Comment by captainsafia** [comment]
@maclockard Is `npm build/test` still passing here?

**Comment by maclockard** [comment]
@captainsafia yes they are!
Screen Shot 2021-03-23 at 3 39 37 PM

**Review by captainsafia — APPROVED** [review]

**Comment by maclockard** [comment]
@captainsafia would it be possible to get a release with this change?

**Comment by captainsafia** [comment]
@nteract/mathjax@4.0.16

I thought I had set up auto-publish on this repo. Guess not.

**Pull request merged**
